{
 "title": "Canary NG",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "name", "query": { "query": "label_values(job_name)" } },
   {
    "name": "query",
    "query": {
     "query": "label_values(canary_ng_duration_bucket,query)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(canary_ng_failures{job_name=~\"${name}\"}[$__interval])",
       "legendFormat": "{{job_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability - $name",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (sum(increase(canary_ng_failures{job_name=~\"${name}\"}[$__rate_interval])) OR vector(0)) / sum(increase(canary_ng_queries{job_name=~\"${name}\"}[$__rate_interval]))",
       "legendFormat": "availabilty"
      }
     ]
    }
   ]
  },
  { "title": "P75", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Latency p75 - $name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le, job_name) (rate(canary_ng_duration_bucket{job_name=~\"${name}\", query=~\"${query}\"}[$__rate_interval])))",
     "legendFormat": "{{sql_job}}"
    }
   ]
  },
  { "title": "P90", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Latency p90 - $name",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le, job_name) (rate(canary_ng_duration_bucket{job_name=~\"${name}\", query=~\"${query}\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "P99", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Latency p99 - $name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, job_name) (rate(canary_ng_duration_bucket{job_name=~\"${name}\", query=~\"${query}\"}[$__rate_interval])))",
     "legendFormat": "{{sql_job}}"
    }
   ]
  }
 ]
}